name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v3
    - uses: gittools/actions/gitversion/setup@v2
      with:
        versionSpec: '5.x'
    - uses: gittools/actions/gitversion/execute@v2
    - run: |
        IMAGE_ID=${{ github.repository }}
        IMAGE_ID=${IMAGE_ID,,}
        echo "image_tag=$IMAGE_ID" >> $GITHUB_ENV
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          VERSION=${{ env.GitVersion_InformationalVersion }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ env.GitVersion_InformationalVersion }}
        push: ${{ github.ref_name == 'master' }}
        tags: ghcr.io/${{ env.image_tag }}:${{ github.sha }},ghcr.io/${{ env.image_tag }}:dev
        cache-from: type=gha
        cache-to: type=gha,mode=max